spring:
  application:
    name: space-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/spaces
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8901