ZENSPACE_CONFIG_JWT_SECRET: "fdaf05402423743dea17eef133a4c2ca5e87f1c86539cf12cea09c401d8374c203042d683df27be3ee6a79f4c4884aaaf77829ade6a4082773ebac35c60a7921"
ZENSPACE_CONFIG_ACCESS_TOKEN_EXPIRATION: 86400000
ZENSPACE_CONFIG_REFRESH_TOKEN_EXPIRATION: 1296000000
spring:
  servlet:
    multipart:
      max-file-size: 1000000MB
      max-request-size: 1000000MB
      enabled: true
  application:
    name: zenspace-server
  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: password
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/zenspace
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8901