services:
  postgres-db:
    image: postgres:17.4-alpine3.21
    container_name: zenspace-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zenspace
    ports:
      - "5432:5432"
  neo4j-db:
    image: neo4j:latest
    container_name: zenspace-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password